export default {
  REPO_LINK: process.env.REACT_APP_REPO_LINK,
  BRAND_NAME: process.env.REACT_APP_BRAND_NAME,
  SITE_URL: process.env.REACT_APP_SITE_URL,
  ENABLED_LANGUAGES: process.env.REACT_APP_ENABLED_LANGUAGES,
  ENABLED_PROVIDER: process.env.REACT_APP_ENABLED_PROVIDER,
  SENTRY_DSN: process.env.REACT_APP_SENTRY_DSN,
  DISCORD_LINK: process.env.REACT_APP_DISCORD_LINK,
  LOGROCKET_ID: process.env.REACT_APP_LOGROCKET_ID,
};
