// https://resources-game.ch/resapi/?q=51&f=1&k=KEY

export default [
  {
    mineID: 4,
    resourceID: 2,
    amount: 0,
    ratePerHour: 0,
    name: 'Clay pit',
    resourceName: 'Clay',
    basePrice: 1_000_000,
    maxRate: 1_530,
  },
  {
    mineID: 5,
    resourceID: 3,
    amount: 0,
    ratePerHour: 0,
    name: 'Gravel pit',
    resourceName: 'Gravel',
    basePrice: 5_000_000,
    maxRate: 542,
  },
  {
    mineID: 9,
    resourceID: 8,
    amount: 0,
    ratePerHour: 0,
    name: 'Coal mine',
    resourceName: 'Coal',
    basePrice: 50_000_000,
    maxRate: 510,
  },
  {
    mineID: 11,
    resourceID: 10,
    amount: 0,
    ratePerHour: 0,
    name: 'Oil derrick',
    resourceName: 'Crude oil',
    basePrice: 100_000_000,
    maxRate: 306,
  },
  {
    mineID: 16,
    resourceID: 12,
    amount: 0,
    ratePerHour: 0,
    name: 'Bauxite mine',
    resourceName: 'Bauxite',
    basePrice: 600_000_000,
    maxRate: 306,
  },
  {
    mineID: 17,
    resourceID: 13,
    amount: 0,
    ratePerHour: 0,
    name: 'Iron ore mine',
    resourceName: 'Iron ore',
    basePrice: 10_000_000,
    maxRate: 382.5,
  },
  {
    mineID: 18,
    resourceID: 14,
    amount: 0,
    ratePerHour: 0,
    name: 'Gold mine',
    resourceName: 'Gold ore',
    basePrice: 1_500_000_000,
    maxRate: 2040,
  },
  {
    mineID: 19,
    resourceID: 15,
    amount: 0,
    ratePerHour: 0,
    name: 'Silver mine',
    resourceName: 'Silver ore',
    basePrice: 1_250_000_000,
    maxRate: 638,
  },
  {
    mineID: 21,
    resourceID: 20,
    amount: 0,
    ratePerHour: 0,
    name: 'limestone quarry',
    resourceName: 'Limestone',
    basePrice: 2_500_000,
    maxRate: 510,
  },
  {
    mineID: 27,
    resourceID: 26,
    amount: 0,
    ratePerHour: 0,
    name: 'Copper mine',
    resourceName: 'Chalcopyrite',
    basePrice: 400_000_000,
    maxRate: 408,
  },
  {
    mineID: 50,
    resourceID: 49,
    amount: 0,
    ratePerHour: 0,
    name: 'Ilmenite mine',
    resourceName: 'Ilmenite',
    basePrice: 1_000_000_000,
    maxRate: 281,
  },
  {
    mineID: 54,
    resourceID: 53,
    amount: 0,
    ratePerHour: 0,
    name: 'Sand mine',
    resourceName: 'Quartz sand',
    basePrice: 200_000_000,
    maxRate: 765,
  },
  {
    mineID: 82,
    resourceID: 81,
    amount: 0,
    ratePerHour: 0,
    name: 'Diamond mine',
    resourceName: 'Rough diamonds',
    basePrice: 2_000_000_000,
    maxRate: 1_275,
  },
  {
    mineID: 89,
    resourceID: 90,
    amount: 0,
    ratePerHour: 0,
    name: 'Lithium ore mine',
    resourceName: 'Lithium ore',
    basePrice: 800_000_000,
    maxRate: 2040,
  },
];
